services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ftr
      - POSTGRES_PASSWORD=ftr
      - POSTGRES_DB=brevly
    volumes:
      - brevly_data:/bitnami/postgresql

volumes:
  brevly_data: