services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ftr
      - POSTGRES_PASSWORD=ftr
      - POSTGRES_DB=brevly
    volumes:
      - './docker:/docker-entrypoint-initdb.d'